### ISSUE TITLE
Create documentation for remaining screens for patient and doctor

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#12]
By screen, break down of api calls and potential inputs and outputs needed to make screen work.

Api call names can be whatever makes sense will fix later.

Inputs outputs can be whatever makes sense.

Remember that with a session ID we know what role the person is already in the api so you don't need to worry about this.

(EXAMPLE)

getProfile:
Inputs:
- sessionID

Outputs:
- name
- address
- city
- state

Please save this as a markdown ml at /docs/logical_screen_api_call_and_data.md

**Comment by aperry567** [comment]
Jinal, has completed this issue. Closing out this issue.  Thanks
