### ISSUE TITLE
update user profile

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#45]
update the user's profile in the database

will include password changes but not email or role

Ensure password passes the complexity checks already in code

Ensure password is hashed like already in code

Must have an audit action as data is changing

add pharmacy location to getProfile and signup api methods.

Ensure doctorLicenses is only set if doctor role

Ensure pharmacyLocation is only set if patient role

**Comment by aperry567** [comment]
Ayana, will take the API calls.  :)

**Comment by aperry567** [comment]
Completed the tasks.

**Comment by jsaterfiel** [comment]
You seem to have just duplicated the getProfile api call.  The input is sessionID + profile and there's no response body just a 200 status for okay or error.  I went ahead and fixed the method name and a syntax error that was preventing me from being able to build locally.

**Comment by aperry567** [comment]
I'm revising my code and will push to my dedicated dev branch.
