### ISSUE TITLE
get visits api call

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#46]
API Options:
- sessionID
- patientID (only valid for sessions with role doctor)

If doctor role then query against doctor_user_id
If patient role then query against patient_user_id

DB Fields:
- VISIT_ID
- PATIENT_USER_ID
- DOCTOR_USER_ID
- VISIT_TIME
- REASON
- NOTES

Return Fields: (list)
- id
- visitTime
- doctor
  - id
  - name
  - photo
- patient
  - id
  - name
  - photo
- reason
- notes

**Comment by aperry567** [comment]
Ayana, will take the API calls.  :)  John likes to hog the fun stuff.
