### ISSUE TITLE
get exams api call

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#47]
API Input:
- sessionID
- showHistory (boolean) (default is false)
- patientID (only valid for sessions with role doctor)

If doctor role then query against doctor_user_id.
If patient role then query against patient_user_id.
If showHistory show all exams before NOW()
if not showHistory show all exams after NOW()

DB Fields:
- EXAM_ID
- PATIENT_USER_ID
- DOCTOR_USER_ID
- VISIT_ID
- EXAM_TIME
- DESC
- LOCATION

Return Fields: (list)
- examID
- visitID
- patient
  - id
  - name
  - photo
- doctor
  - id
  - name
  - photo
- examTime
- description
- location

**Comment by aperry567** [comment]
Created the EXAMS database table.
