### ISSUE TITLE
get prescriptions api call

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#48]
API Inputs:
- sessionID
- patientID (only valid for sessions with role doctor)

If doctor role then query against doctor_user_id (always used even if patientID passed)
If patient role then query against patient_user_id

database fields:
- PERSCRIPTION_ID
- PATIENT_USER_ID
- DOCTOR_USER_ID
- VISIT_ID
- CREATED_TIME (timestamp)
- NAME
- INSTRUCTIONS
- REFILLS (INT)

Return Fields: (list)
- createdTime
- name
- instructions
- visitId
- patient
  - id
  - name
  - photo
- doctor
  - id
  - name
  - photo
- refills (int)

**Comment by aperry567** [comment]
Ayana, will take the API calls.  :)  John likes to hog the fun stuff.

**Comment by aperry567** [comment]
Created database table PRESCRIPTIONS
