### ISSUE TITLE
get/update Prescription api

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#62]
Details screen api call

possibly editable fields are for doctors only
subtitle refills use regex for group selection
refills have to be an integer from [0-20] all else will fail
- title (drug name)
- subtitle (refills: 0)
- details (instructions)

getPrescriptionDetail response (reusable struct)
```
{
title: "<Name>",
titleEditable: true,
subtitle: "Refills: <REFILLS>".
subtitleEditable: true
details: "<INSTRUCTIONS>",
detailsEditable: true
label: "Rx"
labelColor: "0xff24d622"
photo: "" //leave blank
dateTime: "<CREATED_TIME>"
chatURL: "" //leave blank
relatedItemsURL: ""  //leave blank
updateURL: /api/updatePrescription?sessionID=sdfsdf&prescriptionID=123123
}
```

updatePrescription request body (unique per update api call)
```
{
title: "<string>",
subtitle: "<string>",
details: "<string>"
}
```

DB Fields Mapping:
- title => name
- subtitle => refills (use regex to find number will come in as Refills: XXX or any other string combinations)
- details => instructions

**Comment by aperry567** [comment]
(perry) New api prescription is ready
