### ISSUE TITLE
get/update Exam api

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#63]
Details screen api call

possibly editable fields
- subtitle (location)
- dateTime (exam_time)

get response (reusable struct)
```
{
title: "Exam",
photo: "", //leave blank
subtitle: "<Location>"
subtitleEditable: true
dateTime: "<EXAM_TIME>",
dateTimeEditable: true
label: "Exam",
labelColor: "0xff227cd6",
details: "<DESC>",
chatURL: "" //leave blank
relatedItemsURL: ""  //leave blank
updateURL: /api/updateExam?sessionID=sdfsdf&examID=123123
}
```

updateExam request body (unique per update api call)
```
{
subtitle: "<string>",
dateTime: "<string>", //formatted in db format YYYY-MM-DD HH:MM:SS
}
```

DB Fields Mapping:
- subtitle => location
- dateTime => EXAM_TIME

remember that only role doctor can update items

remember to add the detail link to patient home screen.

**Comment by aperry567** [comment]
(perry) New api exam is ready
