### ISSUE TITLE
Setup user tables in database

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#7]
Create a database schema for the user table.

users
- user_id
- email
- creation_dte
- password (must be stored as a hashed value with salt of creation date)
- patient
- address
- string
- postalCode
- phoneNumber
- license

Please add an admin account the email admin@nowhere.com with the password P@ssw0rd into test data

Store the sql creation script in the /db folder

**Comment by aperry567** [comment]
Created the users table and schema.  Need to check the salt for the passwords not sure how to complete that part in gcp.  
Can not create an admin account with the email address specified because you need a gmail account to have admin privileges on GCP.

**Comment by aperry567** [comment]
The sql creation script now resides on the /db folder location.
