### ISSUE TITLE
findADoctor api call

### ISSUE THREAD

**Issue by jsaterfiel** [aperry567/SSW690B#73]
After going through health questionnaire api, you get a link on the final question to findADoctor with the final question id.

This call will use the final question id to determine which doc specialties can be used for this visit, compiles a response list view of the doctors in the same state as the user that have this specialities returned in alphabetical order.

Doctor Card:
Title: Name
SubTitle: City, State
Pic of doctor

Detail link is to the creeateVisit api call with the id of the doctor and the final question

**Comment by aperry567** [comment]
Completed.
